name: suite2p
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libopenblas=0.3.25
  - libsodium=1.0.18
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numba=0.60.0
  - openssl=3.4.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.2.2
  - pooch=1.8.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - allensdk==2.16.2
      - anyio==4.8.0
      - anytree==2.12.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argschema==3.0.4
      - arrow==1.3.0
      - astroid==3.3.8
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blosc2==2.7.1
      - boto3==1.37.33
      - botocore==1.37.33
      - cachetools==5.5.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - distro==1.9.0
      - elephant==1.1.1
      - faiss-cpu==1.10.0
      - fastcluster==1.2.6
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - filterpy==1.4.5
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - future==1.0.0
      - glymur==0.14.1.post1
      - h11==0.14.0
      - h5py==3.11.0
      - hdmf==4.0.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - igraph==0.11.8
      - imageio==2.37.0
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==5.13.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kilosort==4.0.24
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - louvain==0.8.2
      - lxml==5.3.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matlab==0.1
      - matlab-kernel==0.17.1
      - matlabengine==24.1.2
      - matplotlib==3.9.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - metakernel==0.30.2
      - mistune==3.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - ndindex==1.9.2
      - ndx-events==0.2.1
      - neo==0.14.0
      - networkx==3.3
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numexpr==2.10.2
      - numpy==1.23.5
      - overrides==7.7.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pillow==10.4.0
      - pip==25.0.1
      - pprintpp==0.4.0
      - prometheus-client==0.21.1
      - propcache==0.3.1
      - psycopg2-binary==2.9.10
      - py-cpuinfo==9.0.0
      - pylint==3.3.3
      - pynrrd==1.1.3
      - pynwb==2.8.3
      - pyparsing==3.1.2
      - python-json-logger==3.2.1
      - pytz==2024.1
      - pyyaml==6.0.2
      - quantities==0.16.1
      - rastermap==1.0
      - referencing==0.36.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.11.4
      - scikit-build==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - semver==3.0.4
      - send2trash==1.8.3
      - simpleitk==2.4.1
      - simplejson==3.20.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tables==3.10.2
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2025.3.30
      - tinycss2==1.4.0
      - tomlkit==0.13.2
      - torch==2.6.0
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.1
      - uri-template==1.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wurlitzer==3.1.1
      - xarray==2023.1.0
      - yarl==1.19.0
